name: The Kiefer Likens
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191919'
    - '#6d6d6d'
    - '#f8ae4c'
    - '#ffffff'
    - '#cfcfcf'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
