name: The Kiefer Likens
favicon: null
layout_spectrum: 0.14471865817904472
typography_spectrum: 0.32656866614706814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07174533931538463
  lightness: 0.41001351666636765
  saturation: 0.3857594847213477
  rhythmicContrast: 0.31955076358281076
purpose: []
